### ISSUE TITLE
[TECH] init language change strategy

### ISSUE THREAD

**Issue by Reizlina** [Dergelyova/team-404#18]

**Comment by Dergelyova** [comment]
Docs

[static-i18n](https://www.npmjs.com/package/static-i18n) library is used for this feature

To create multiple lang files

Create in `src/partials/locales` key-value translations for every language.


![Image](https://user-images.githubusercontent.com/88082907/213933567-b6235993-e8bf-4516-aefb-1bb9d9065f5d.png)



![Image](https://user-images.githubusercontent.com/88082907/213933572-062f9959-363b-4b77-895a-1540dde9f435.png)



![Image](https://user-images.githubusercontent.com/88082907/213933590-692f5692-7db0-4d4c-a3fd-e3525a579a18.png)


=====================================================
Put in `src/partials` html-files attribute `data-t` and innerHtml must contain path to parts.

![Image](https://user-images.githubusercontent.com/88082907/213933619-2daea2bf-01a6-4602-9f0d-fbeb9c96b663.png)

=====================================================
Run `npm run translate` to generate i18n files with updated parts

=====================================================

After creating new partial all 3 language html files in `src` directory  must be updated with proper relative path to i18n translated file. 
Base .html (for ukr files)
en-....html (for eng files)
ru-.....html (for rus files)


![Image](https://user-images.githubusercontent.com/88082907/213933806-a17b7228-d5af-43c3-b285-95f7d5227b4e.png)
